### ISSUE TITLE
code release? 

### ISSUE THREAD

**Issue by jiafengshen** [qingshi9974/ECCV2024-AdpatICMH#1]

**Comment by qingshi9974** [comment]
你好，paper附录中包含了核心模块的实现代码，训练代码可参考TransTIC。由于最近一直在赶文章，完整的训练代码和模型预计10月初会整理好发布在github上。

**Comment by jiafengshen** [comment]
你好，问个问题，这个是针对每个机器视觉任务都要单独微调一个ICMH，还是就训好后适配任何机器视觉任务，即对后续任务不感知

**Comment by qingshi9974** [comment]
> 你好，问个问题，这个是针对每个机器视觉任务都要单独微调一个ICMH，还是就训好后适配任何机器视觉任务，即对后续任务不感知

文章中的方案是每个机器视觉任务都要单独微调一个ICMH，这样task-spcific的训练方式性能会更好一些。我这边也测试过，如果在分类任务上进行训练，直接应用到检测和分割上的话效果还是不错的。但如果在分割或检测上训练，直接应用到另外两个任务上，性能会下降不少。

**Comment by jiafengshen** [comment]
具体是不是体现再损失函数上，不同的分割模型有影响吗，比如我用自己的分割模型训的，但用其他人的分割模型去训练

**Comment by jiafengshen** [comment]
具体是不是体现在损失函数上，不同的分割模型有影响吗，比如我用自己的分割模型训的，但用其他人的分割模型去测试

**Comment by jiafengshen** [comment]
你好

**Comment by qingshi9974** [comment]
> 具体是不是体现在损失函数上，不同的分割模型有影响吗，比如我用自己的分割模型训的，但用其他人的分割模型去测试

不同任务的损失函数是不一样的，主要取决于下游预训练好的模型。你这个场景我没有测试过，但是理论上都是分割的话，应该不会有明显的性能差别

**Comment by DSFDSFSer2** [comment]
您好，请问代码什么时候开放，想深入学习

**Comment by qingshi9974** [comment]
> 您好，请问代码什么时候开放，想深入学习

您好，代码已经开源了，模型将会在后续陆续上传

**Comment by DSFDSFSer2** [comment]
非常感谢
